import { Kantumruy_Pro, Noto_Sans_SC, Poppins } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";

const KantumruyFont = Kantumruy_Pro({
  variable: "--font-kantumruy",
  subsets: ["khmer"],
});

const PoppinsFont = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const NatoSansSCFont = Noto_Sans_SC({
  variable: "--font-notosanssc",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${KantumruyFont.variable} ${PoppinsFont.variable}  ${NatoSansSCFont.variable} antialiased lang-en`}
      >
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
